import os
import uuid
from flask import Flask, render_template, request, redirect, url_for, session
from database import get_db_connection

from crypto_utils import (
    generate_aes_key,
    encrypt_message,
    decrypt_message,
    encrypt_aes_key,
    decrypt_aes_key,
    generate_hmac,
    verify_hmac
)

from key_manager import load_or_generate_keys
from werkzeug.security import generate_password_hash, check_password_hash


app = Flask(__name__)

app.secret_key = "secure-internet-communication-project-key"


# ---------------- HOME ----------------

@app.route("/")
def home():
    return redirect(url_for("login"))


# ---------------- REGISTER ----------------

@app.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        username = request.form["username"].strip()
        password = request.form["password"]

        if not username or not password:
            return "Username and password are required."

        password_hash = generate_password_hash(password)

        connection = get_db_connection()
        cursor = connection.cursor()

        try:

            cursor.execute(
                """
                INSERT INTO users (username, password_hash)
                VALUES (%s, %s)
                """,
                (username, password_hash)
            )

            connection.commit()

        except Exception:

            connection.rollback()
            cursor.close()
            connection.close()

            return "Username already exists. Please choose another username."

        cursor.close()
        connection.close()

        return redirect(url_for("login"))

    return render_template("register.html")


# ---------------- LOGIN ----------------

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        username = request.form["username"].strip()
        password = request.form["password"]

        connection = get_db_connection()
        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT id, username, password_hash
            FROM users
            WHERE username = %s
            """,
            (username,)
        )

        user = cursor.fetchone()

        cursor.close()
        connection.close()

        if user and check_password_hash(user[2], password):

            session["user_id"] = user[0]
            session["username"] = user[1]

            return redirect(url_for("dashboard"))

        return "Invalid username or password."

    return render_template("login.html")


# ---------------- LOGOUT ----------------

@app.route("/logout")
def logout():

    session.clear()

    return redirect(url_for("login"))


# ---------------- DASHBOARD ----------------

@app.route("/dashboard")
def dashboard():

    if "user_id" not in session:
        return redirect(url_for("login"))

    return render_template(
        "dashboard.html",
        username=session["username"]
    )

@app.route("/security")
def security():

    if "user_id" not in session:
        return redirect(url_for("login"))

    return render_template(
        "security.html",
        username=session["username"]
    )
# ---------------- SEND MESSAGE ----------------

@app.route("/send", methods=["GET", "POST"])
def send_message():

    if "user_id" not in session:
        return redirect(url_for("login"))

    connection = get_db_connection()
    cursor = connection.cursor()

    # Get all users except current user
    cursor.execute(
        """
        SELECT username
        FROM users
        WHERE username != %s
        ORDER BY username
        """,
        (session["username"],)
    )

    users = cursor.fetchall()

    if request.method == "POST":

        receiver = request.form["receiver"].strip()
        message = request.form["message"].strip()

        if not receiver or not message:
            cursor.close()
            connection.close()

            return "Receiver and message are required."

        # Verify receiver exists
        cursor.execute(
            """
            SELECT username
            FROM users
            WHERE username = %s
            """,
            (receiver,)
        )

        receiver_exists = cursor.fetchone()

        if not receiver_exists:

            cursor.close()
            connection.close()

            return "Receiver does not exist."

        # Get the unique request ID generated by the browser
        request_id = request.form.get("request_id", "").strip()

        if not request_id:
            cursor.close()
            connection.close()

            return "Security Error: Missing request ID."
        # Check whether this request ID was already processed
        cursor.execute(
            """
            SELECT id
            FROM messages
            WHERE request_id = %s
            """,
            (request_id,)
        )

        existing_request = cursor.fetchone()

        if existing_request:
            cursor.close()
            connection.close()

            return "Security Error: Replay attack detected."
        # Generate AES-256 key
        aes_key = generate_aes_key()

        # Load persistent RSA-2048 keys
        private_key, public_key = load_or_generate_keys()

        # Encrypt message using AES-256-GCM
        nonce, encrypted_message = encrypt_message(
            message,
            aes_key
        )

        # Protect AES key using RSA-2048
        encrypted_aes_key = encrypt_aes_key(
            aes_key,
            public_key
        )

        # Generate HMAC-SHA256
        message_hmac = generate_hmac(
            encrypted_message,
            aes_key
        )

        # Verify integrity before storing
        integrity_verified = verify_hmac(
            encrypted_message,
            message_hmac,
            aes_key
        )

        # Store encrypted message
        cursor.execute(
            """
            INSERT INTO messages
            (
                sender,
                receiver,
                request_id,
                encrypted_message,
                nonce,
                encrypted_aes_key,
                hmac
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            (
                session["username"],
                receiver,
                request_id,
                encrypted_message.hex(),
                nonce.hex(),
                encrypted_aes_key.hex(),
                message_hmac.hex()
            )
        )

        connection.commit()

        cursor.close()
        connection.close()

        return render_template(
            "message_result.html",
            sender=session["username"],
            receiver=receiver,
            integrity_verified=integrity_verified,
            encrypted_message=encrypted_message.hex(),
            encrypted_aes_key=encrypted_aes_key.hex(),
            message_hmac=message_hmac.hex()
        )

    cursor.close()
    connection.close()

    return render_template(
        "send.html",
        username=session["username"],
        users=users
    )


# ---------------- INBOX ----------------

@app.route("/inbox")
def inbox():

    if "user_id" not in session:
        return redirect(url_for("login"))

    private_key, public_key = load_or_generate_keys()

    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute(
        """
        SELECT
            id,
            sender,
            receiver,
            encrypted_message,
            nonce,
            encrypted_aes_key,
            hmac,
            created_at
        FROM messages
        WHERE receiver = %s
        ORDER BY id DESC
        """,
        (session["username"],)
    )

    stored_messages = cursor.fetchall()

    cursor.close()
    connection.close()

    decrypted_messages = []

    for stored_message in stored_messages:

        try:

            message_id = stored_message[0]
            sender = stored_message[1]
            receiver = stored_message[2]

            encrypted_message = bytes.fromhex(
                stored_message[3]
            )

            nonce = bytes.fromhex(
                stored_message[4]
            )

            encrypted_aes_key = bytes.fromhex(
                stored_message[5]
            )

            received_hmac = bytes.fromhex(
                stored_message[6]
            )

            created_at = stored_message[7]

            # Recover AES key using RSA private key
            aes_key = decrypt_aes_key(
                encrypted_aes_key,
                private_key
            )

            # Verify message integrity
            integrity_verified = verify_hmac(
                encrypted_message,
                received_hmac,
                aes_key
            )

            if integrity_verified:

                decrypted_message = decrypt_message(
                    nonce,
                    encrypted_message,
                    aes_key
                )

            else:

                decrypted_message = (
                    "Security Error: "
                    "Message integrity verification failed."
                )

            decrypted_messages.append(
                {
                    "id": message_id,
                    "sender": sender,
                    "receiver": receiver,
                    "message": decrypted_message,
                    "created_at": created_at,
                    "integrity_verified": integrity_verified
                }
            )

        except Exception:

            decrypted_messages.append(
                {
                    "id": stored_message[0],
                    "sender": stored_message[1],
                    "receiver": stored_message[2],
                    "message": "Decryption failed.",
                    "created_at": stored_message[7],
                    "integrity_verified": False
                }
            )

    return render_template(
        "receive.html",
        messages=decrypted_messages,
        username=session["username"]
    )


# ---------------- SENT MESSAGES ----------------

@app.route("/sent")
def sent_messages():

    if "user_id" not in session:
        return redirect(url_for("login"))

    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute(
        """
        SELECT
            id,
            sender,
            receiver,
            encrypted_message,
            created_at
        FROM messages
        WHERE sender = %s
        ORDER BY id DESC
        """,
        (session["username"],)
    )

    messages = cursor.fetchall()

    cursor.close()
    connection.close()

    return render_template(
        "messages.html",
        messages=messages,
        username=session["username"]
    )


# ---------------- OLD ROUTES ----------------

@app.route("/chat")
def chat():

    if "user_id" not in session:
        return redirect(url_for("login"))

    return redirect(url_for("send_message"))


@app.route("/receive")
def receive():

    return redirect(url_for("inbox"))


@app.route("/messages")
def messages():

    return redirect(url_for("sent_messages"))


# ---------------- RUN APPLICATION ----------------

if __name__ == "__main__":

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    CERT_FILE = os.path.join(
        BASE_DIR,
        "certs",
        "cert.pem"
    )

    KEY_FILE = os.path.join(
        BASE_DIR,
        "certs",
        "key.pem"
    )

    app.run(
        host="127.0.0.1",
        port=5000,
        debug=True,
        ssl_context=(CERT_FILE, KEY_FILE)
    )